dist: xenial # Required for Python >= 3.7
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then pipenv run pip install pip==18.0; fi
  - pipenv sync
script:
  - pipenv run pytest
